config/routes.rb
Rails.application.routes.draw do

  get 'publications/new'
  get 'publications/create'
  get 'publications/edit'
  get 'publications/show'
  get 'publications/index'
  get 'publications/update'
  get 'publications/destroy'
  get 'avatars/create'
  get 'avatars/show'
  root 'static_pages#index'
  resources :requests
  resources :events do
    resources :commentaire
    resources :likes
  end
  resources :recrutements
  resources :clubs do
  	resources :pictures
  end
  resources :quarters
  devise_for :users
  resources :users do
    resources :avatars
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  include Trestle::Auth::ModelMethods
  include Trestle::Auth::ModelMethods::Rememberable
end

app/models/club.rb
class Club < ApplicationRecord
	belongs_to :admin, class_name: 'User', dependent: :destroy
	belongs_to :quarter, dependent: :destroy
	has_many :recrutements
	has_many :members, class_name: 'User'
	has_many :participants, through: :recrutements
	has_many :events
	has_one_attached :picture
end

app/models/commentaire.rb
class Commentaire < ApplicationRecord
	validates :content, presence: true
	belongs_to :user
	belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :club, dependent: :destroy
	has_many :commentaires	
	has_many :likes, dependent: :destroy

end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :event
	belongs_to :user
end

app/models/publication.rb
class Publication < ApplicationRecord
	belongs_to :user, dependent: :destroy
end

app/models/quarter.rb
class Quarter < ApplicationRecord
	has_many :clubs
	has_many :users
end

app/models/recrutement.rb
class Recrutement < ApplicationRecord
	has_many :requests
	belongs_to :club, dependent: :destroy
end

app/models/request.rb
class Request < ApplicationRecord
	belongs_to :recrutement, dependent: :destroy, dependent: :destroy
	belongs_to :user, dependent: :destroy
end

app/models/router.rb
class Router < ApplicationRecord
end

app/models/static_page.rb
class StaticPage < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         belongs_to :quarter, optional: true
         belongs_to :club, optional: true
         has_many :requests
         has_many :commentaires
         has_many :likes, dependent: :destroy
         has_one_attached :avatar
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    @events = Event.all
    @recrutements = Recrutement.all
    @clubs = Club.all
  end
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/quarters_helper.rb
module QuartersHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/routers_helper.rb
module RoutersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/static_pages/_form.html.erb
<%= form_with(model: static_page, local: true) do |form| %>
  <% if static_page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(static_page.errors.count, "error") %> prohibited this static_page from being saved:</h2>

      <ul>
        <% static_page.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/static_pages/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">MalagSport</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Se connecter/S'inscrire
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Se connecter</a>
          <a class="dropdown-item" href="#">S'inscrire</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
    </ul>
  </div>
</nav>


<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <div class="banner" style="background-image: url();"></div>
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="..." class="d-block w-100" alt="...">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/static_pages/edit.html.erb
<h1>Editing Static Page</h1>

<%= render 'form', static_page: @static_page %>

<%= link_to 'Show', @static_page %> |
<%= link_to 'Back', static_pages_path %>

app/views/static_pages/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Malagasport</title>
  <meta name="Groupe03" content="Malagasport">
  

  <!-- Font Awesome if you need it-->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">
  
  <link rel="stylesheet" href="https://unpkg.com/tailwindcss/dist/tailwind.min.css">
  <!--Replace with your tailwind.css once created-->

  <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,700" rel="stylesheet">


      <!-- ==============================================
    CSS
    =============================================== -->
        <link type="text/css" href="/vendor/css/demos/photo.css" rel="stylesheet" />
        
    <!-- ==============================================
    Feauture Detection
    =============================================== -->
    <script src="/vendor/js/modernizr-custom.js"></script>

  <!-- Define your gradient here - use online tools to find a gradient matching your branding-->
  

</head>

<body class="leading-normal tracking-normal text-white gradient" style="font-family: 'Source Sans Pro', sans-serif;">





<!--effets riviere-->
<div class="relative -mt-12 lg:-mt-24">
  <svg viewBox="0 0 1428 174" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
  <g transform="translate(-2.000000, 44.000000)" fill="#FFFFFF" fill-rule="nonzero">
  <path d="M0,0 C90.7283404,0.927527913 147.912752,27.187927 291.910178,59.9119003 C387.908462,81.7278826 543.605069,89.334785 759,82.7326078 C469.336065,156.254352 216.336065,153.6679 0,74.9732496" opacity="0.100000001"></path>
  <path d="M100,104.708498 C277.413333,72.2345949 426.147877,52.5246657 546.203633,45.5787101 C666.259389,38.6327546 810.524845,41.7979068 979,55.0741668 C931.069965,56.122511 810.303266,74.8455141 616.699903,111.243176 C423.096539,147.640838 250.863238,145.462612 100,104.708498 Z" opacity="0.100000001"></path>
  <path d="M1046,51.6521276 C1130.83045,29.328812 1279.08318,17.607883 1439,40.1656806 L1439,120 C1271.17211,77.9435312 1140.17211,55.1609071 1046,51.6521276 Z" id="Path-4" opacity="0.200000003"></path>
  </g>
  <g transform="translate(-4.000000, 76.000000)" fill="#FFFFFF" fill-rule="nonzero">
  <path d="M0.457,34.035 C57.086,53.198 98.208,65.809 123.822,71.865 C181.454,85.495 234.295,90.29 272.033,93.459 C311.355,96.759 396.635,95.801 461.025,91.663 C486.76,90.01 518.727,86.372 556.926,80.752 C595.747,74.596 622.372,70.008 636.799,66.991 C663.913,61.324 712.501,49.503 727.605,46.128 C780.47,34.317 818.839,22.532 856.324,15.904 C922.689,4.169 955.676,2.522 1011.185,0.432 C1060.705,1.477 1097.39,3.129 1121.236,5.387 C1161.703,9.219 1208.621,17.821 1235.4,22.304 C1285.855,30.748 1354.351,47.432 1440.886,72.354 L1441.191,104.352 L1.121,104.031 L0.457,34.035 Z"></path>
  </g>
  </g>
  </svg>
</div>




<section class="newsfeed">
    <div class="container-fluid">
     <div class="row">
      <div class="col-lg-3">
      <a href="<%= clubs_path%>">
     <div class="storybox" 
       style="background: linear-gradient( rgba(34,34,34,0.30), rgba(34,34,34,0.78)), url('vendor/jangla.gif') no-repeat;
              background-size: cover;
                  background-position: center center;
                  -webkit-background-size: cover;
                  -moz-background-size: cover;
                  -o-background-size: cover;">
          <div class="story-body text-center">
           <div class=""><img class="img-circle" src="vendor/jangla.gif" alt="user"></div>
            <h3>club</h3>
          </div>      
     </div>
</a>
 <a href="<%= recrutements_path%>">
 <div class="storybox" 
       style="background: linear-gradient( rgba(34,34,34,0.30), rgba(34,34,34,0.78)), url('vendor/recru.gif') no-repeat;
              background-size: cover;
                  background-position: center center;
                  -webkit-background-size: cover;
                  -moz-background-size: cover;
                  -o-background-size: cover;">

          <div class="story-body text-center">
           <div class=""><img class="img-circle" src="vendor/recru.gif" alt="user"></div>
            <h3>Recrutement</h3>
          </div>      
     </div>
</a>

 <a href="<%= events_path%>">
 <div class="storybox" 
       style="background: linear-gradient( rgba(34,34,34,0.30), rgba(34,34,34,0.78)), url('vendor/voalavo.gif') no-repeat;
              background-size: cover;
                  background-position: center center;
                  -webkit-background-size: cover;
                  -moz-background-size: cover;
                  -o-background-size: cover;">

          <div class="story-body text-center">
           <div class=""><img class="img-circle" src="vendor/voalavo.gif" alt="user"></div>
            <h3>Evenement</h3>
          </div>      
     </div>
</a>

    



    
        <div class="trending-box hidden-xs hidden-md">
     <div class="row">
      <div class="col-lg-12">
        <a href="photo_stories.html"><h4>More stories</h4></a>
      </div>
     </div>
        </div>
     
    </div><!--/ col-lg-3 -->


      <div class="col-lg-6">
    









          <% eve = [] %>
          <% rec = [] %>
          <% clu = [] %>
            <% @events.each do |event| %>
            <% eve << event %>
            <%end%>

            <% @recrutements.each do |recrutement| %>
            <% rec << recrutement %>
            <%end%>

            <% @clubs.each do |club| %>
            <% clu << club %>
            <%end%>

            <% 5.times do |i| %>
 <div class="cardbox">
     
          <div class="cardbox-heading">
           <!-- START dropdown-->
           <div class="dropdown pull-right">
             <%= link_to "afficher", event_path(eve[(i+1)*(-1)].id), :class=>"btn btn-info" %> 
           
           </div><!--/ dropdown -->
           <!-- END dropdown-->
           <div class="media m-0">
            <div class="d-flex mr-3">
       <a href="#"><img class="img-responsive img-circle" src="vendor/event.jpeg" alt="User"></a>
      </div>
            <div class="media-body">
             <p class="m-0"><em>Evenement creer par: </em><strong class="a"><%= eve[(i+1)*(-1)].club.name %></strong></p>
             <style type="text/css">
               .a{
                font-size: 20px;
               }

               .b{
                text-align: center;
                color: black;
               }
             </style>
       <small><span>publié le <%= eve[(i+1)*(-1)].updated_at %></span></small>


            </div>
           </div><!--/ media -->
          </div><!--/ cardbox-heading -->
          
      <div class="cardbox-item">

      
      </div><!--/ cardbox-item -->
      <div class= "b">
        
          <h3 style="color: rgb(0,0,400);"><%= eve[(i+1)*(-1)].title%></h3>
          <p><%= eve[(i+1)*(-1)].description%></p>
          <p>Paff: <strong><%= eve[(i+1)*(-1)].price%></strong> $</p>
      </div>
          <div class="cardbox-like">
       <ul>

<%user_like = []%>


<% eve[(i+1)*(-1)].likes.each do |like| %>
  <% if like.user == current_user%>
    <% user_like << like.user.id %>
  <%end%>
<%end%>


<% if user_like.count > 0 %>
    <li><a>j'aime deja</a><span><%= eve[(i+1)*(-1)].likes.count %> </span></li>

<%else%>

      <li><a href="/events/<%=eve[(i+1)*(-1)].id%>/likes"  data-method = "post"><%= (eve[(i+1)*(-1)].likes.count) == 1 ? 'Like' : 'Likes'%></a><span><%= eve[(i+1)*(-1)].likes.count %> </span></li>
<%end%>
        <li><a href="/events/<%=eve[(i+1)*(-1)].id %>/commentaire" title="" class="com">Commentaire </a> <span class="span-last"><%= eve[(i+1)*(-1)].commentaires.all.count %></span></li>
       </ul>
          </div><!--/ cardbox-like -->        
                
     </div><!--/ cardbox -->  





     <div class="cardbox">
     
          <div class="cardbox-heading">
           <!-- START dropdown-->
           <div class="dropdown pull-right">
          
         <%= link_to "afficher", recrutement_path(rec[(i+1)*(-1)].id), :class=>"btn btn-info" %> 
    
           
           </div><!--/ dropdown -->
           <!-- END dropdown-->
           <div class="media m-0">
            <div class="d-flex mr-3">
       <a href="#"><img class="img-responsive img-circle" src="vendor/recrutement.jpeg" alt="User"></a>
      </div>
            <div class="media-body">
             <p class="m-0"><strong class="a"><%= rec[(i+1)*(-1)].club.name %></strong><em>   recrute </em></p>
             <style type="text/css">
               .a{
                font-size: 20px;
               }

               .b{
                text-align: center;
               }
             </style>
       <small><span>publié le <%= rec[(i+1)*(-1)].updated_at %></span></small>


            </div>
           </div><!--/ media -->
          </div><!--/ cardbox-heading -->
          
      <div class="cardbox-item">

      
          </div><!--/ cardbox-item -->
      <div class= "b">
        
          <h3><%= rec[(i+1)*(-1)].content%></h3>
          <p style="color: rgb(500,20,100);"> date limite d'inscription:    <strong><%= rec[(i+1)*(-1)].deadline%></strong></p>
     


      </div>
          <div class="cardbox-like">
       <ul>
      <li><a href="#"></a><span> like</span></li>
        <li><a href="#" title="" class="com"></i></a> <span class="span-last"> comment</span></li>
       </ul>
          </div><!--/ cardbox-like -->        
                
     </div><!--/ cardbox -->  





<%end%>

</div>




<div class="col-lg-3">

    
  <div class="suggestion-box full-width">
    
    </div> 
  <div class="suggestion-box full-width" style="background-image: url(/vendor/coup.jpeg);text-align: center; color:black">
    <div>
      <h3 style="background-color: rgb(50,200,60);">Evénement dans ... minutes</h3>
      <h2><%= eve[eve.count - 1].title%></h2>
    </div>
    
    <div class="cardbox-like">
      <strong style="background-color: white">Deviner qui va gagner et parier</strong>
      <ul>
        <% cote = rand(1..100)%>
        <li><a href="#" class="com">Equipe A</a><span> <%= cote %> %</span></li>
        <li><span> <%=100 - cote %> %</span><a href="#" title="" class="com">Equipe B</a> </li>
      </ul>
    </div><!--/ cardbox-like -->        
                
  </div><!--/ cardbox -->  

  <div class="trending-box">
    <div class="row">
      <div class="col-lg-12">
        <h2>PARTENAIRES</h2>
      </div>
    </div>
  </div>
    
        <div class="trending-box">
          <img src="/vendor/a.jpg">
        </div>
        <div class="trending-box">
          <img src="/vendor/b.jpg">
        </div>
        <div class="trending-box">
          <img src="/vendor/c.jpg">
        </div>
        <div class="trending-box">
          <img src="/vendor/d.jpg">
        </div>
        <div class="trending-box">
          <img src="/vendor/e.jpg">
        </div>

    
    
    </div>
  </div>
</div>



</section>






















  <!-- jQuery if you need it
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  -->

<script>

  var scrollpos = window.scrollY;
  var header = document.getElementById("header");
  var navcontent = document.getElementById("nav-content");
  var navaction = document.getElementById("navAction");
  var brandname = document.getElementById("brandname");
  var toToggle = document.querySelectorAll(".toggleColour");

  document.addEventListener('scroll', function() {

  /*Apply classes for slide in bar*/
  scrollpos = window.scrollY;

    if(scrollpos > 10){
      header.classList.add("bg-white");
    navaction.classList.remove("bg-white");
    navaction.classList.add("gradient");
    navaction.classList.remove("text-gray-800");
    navaction.classList.add("text-white");
    //Use to switch toggleColour colours
      for (var i = 0; i < toToggle.length; i++) {
       toToggle[i].classList.add("text-gray-800");
     toToggle[i].classList.remove("text-white");
    }
    header.classList.add("shadow");
    navcontent.classList.remove("bg-gray-100");
    navcontent.classList.add("bg-white");
    }
    else {
    header.classList.remove("bg-white");
    navaction.classList.remove("gradient");
    navaction.classList.add("bg-white");
    navaction.classList.remove("text-white");
    navaction.classList.add("text-gray-800");
    //Use to switch toggleColour colours
      for (var i = 0; i < toToggle.length; i++) {
       toToggle[i].classList.add("text-white");
     toToggle[i].classList.remove("text-gray-800");
    }
    
    header.classList.remove("shadow");
    navcontent.classList.remove("bg-white");
    navcontent.classList.add("bg-gray-100");
    
    }

  });

  
</script>

<script>
  
  
  /*Toggle dropdown list*/
  /*https://gist.github.com/slavapas/593e8e50cf4cc16ac972afcbad4f70c8*/
  
  var navMenuDiv = document.getElementById("nav-content");
  var navMenu = document.getElementById("nav-toggle");
  
  document.onclick = check;
  function check(e){
    var target = (e && e.target) || (event && event.srcElement);
    
    //Nav Menu
    if (!checkParent(target, navMenuDiv)) {
    // click NOT on the menu
    if (checkParent(target, navMenu)) {
      // click on the link
      if (navMenuDiv.classList.contains("hidden")) {
      navMenuDiv.classList.remove("hidden");
      } else {navMenuDiv.classList.add("hidden");}
    } else {
      // click both outside link and outside menu, hide menu
      navMenuDiv.classList.add("hidden");
    }
    }
    
  }
  function checkParent(t, elm) {
    while(t.parentNode) {
    if( t == elm ) {return true;}
    t = t.parentNode;
    }
    return false;
  }
</script>


</body>

</html>

app/views/static_pages/new.html.erb
<h1>New Static Page</h1>

<%= render 'form', static_page: @static_page %>

<%= link_to 'Back', static_pages_path %>

app/views/static_pages/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_static_page_path(@static_page) %> |
<%= link_to 'Back', static_pages_path %>