config/routes.rb
Rails.application.routes.draw do

  get 'publications/new'
  get 'publications/create'
  get 'publications/edit'
  get 'publications/show'
  get 'publications/index'
  get 'publications/update'
  get 'publications/destroy'
  get 'avatars/create'
  get 'avatars/show'
  root 'static_pages#index'
  resources :requests
  resources :events do
    resources :commentaire
    resources :likes
  end
  resources :recrutements
  resources :clubs do
  	resources :pictures
  end
  resources :quarters
  devise_for :users
  resources :users do
    resources :avatars
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  include Trestle::Auth::ModelMethods
  include Trestle::Auth::ModelMethods::Rememberable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/club.rb
class Club < ApplicationRecord
	belongs_to :admin, class_name: 'User', dependent: :destroy
	belongs_to :quarter, dependent: :destroy
	has_many :recrutements
	has_many :members, class_name: 'User'
	has_many :participants, through: :recrutements
	has_many :events
	has_one_attached :picture
end

app/models/commentaire.rb
class Commentaire < ApplicationRecord
	validates :content, presence: true
	belongs_to :user
	belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :club, dependent: :destroy
	has_many :commentaires	
	has_many :likes, dependent: :destroy

end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :event
	belongs_to :user
end

app/models/publication.rb
class Publication < ApplicationRecord
	belongs_to :user, dependent: :destroy
end

app/models/quarter.rb
class Quarter < ApplicationRecord
	has_many :clubs
	has_many :users
end

app/models/recrutement.rb
class Recrutement < ApplicationRecord
	has_many :requests
	belongs_to :club, dependent: :destroy
end

app/models/request.rb
class Request < ApplicationRecord
	belongs_to :recrutement, dependent: :destroy, dependent: :destroy
	belongs_to :user, dependent: :destroy
end

app/models/router.rb
class Router < ApplicationRecord
end

app/models/static_page.rb
class StaticPage < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         belongs_to :quarter, optional: true
         belongs_to :club, optional: true
         has_many :requests
         has_many :commentaires
         has_many :likes, dependent: :destroy
         has_one_attached :avatar
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		@quarters = Quarter.all
	end

	def show
		@user = User.find(params[:id])
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		
		puts "*"*60
		puts params
      if @user.update(email: "")
        
        puts "*"*60
		puts params
		flash[:success] = 'Votre profil a été mise à jour'
        redirect_to user_path
        
      else
      	flash[:success] = 'Il a eu une erreur dans votre action, veuillez réessayer'
        render '/users/#{@user.id}/edit'
      end
	end
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/quarters_helper.rb
module QuartersHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/routers_helper.rb
module RoutersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
 <%= form_for @user, method: :put  do |f| %>

 <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :gender %><br />
    <%= f.select(:gender, ['Masculin', 'Féminin'], { :class => 'my_style_class' }) %>
  </div>

  <div class="field">
    <%= f.label :pseudonym %><br />
    <%= f.text_field :pseudonym %>
  </div>

  <div class="field">
    <%= f.label :quarter %><br />
    <%= f.select :quarter_id, Quarter.all.map{ |c| [c.name, c.id] } %>
  </div>

  
<div class="actions">
    <%= f.submit "Mettre à jour" %>
  </div>
<% end %>

<%= link_to "Back", :back %>

app/views/users/show.html.erb
<% if @user == current_user %>
<h1>Mon profil</h1>
<br>

	<%if @user.avatar.attached?%>
		<%= image_tag @user.avatar, alt: 'avatar', :class=>"pdp" %>
		<br>
		<strong> <%=link_to'Modifier ma photos de profil', edit_user_avatar_path(@user.id)%> </strong>
		<br>
	<%else%>
		<strong> <%=link_to'Ajouter une photos de profil', new_user_avatar_path(@user.id)%> </strong><br>
	<%end%>
	<br>

<h1>Apropos de <%= @user.pseudonym %></h1>
<%end%>
<ul>
	<li>Pseudo: <%= @user.pseudonym%> </li>
	<li>Prénom: <%= @user.first_name%> </li>
	<li>Nom: <%= @user.last_name%> </li>
	<li>Email: <%= @user.email%> </li>
	<li>Age: <%= @user.age%> </li>
	<li>Genre: <%= @user.gender%> </li>
	<li>Description: <%= @user.description%> </li>
	<% if @user.quarter != nil%>
	<li>Quartier:<%= link_to "#{@user.quarter.name}", quarter_path(@user.quarter.id)%> </li>
	<% unless @user.club == nil %>
	<li>Club: <%= link_to "#{@user.club.name}", club_path(@user.club.id) %> </li>
	<% end %>
	<% end %>
</ul>
	<%= link_to "Mettre à jour mon compte", edit_user_registration_path(current_user.id)%>

<style type="text/css">
	.pdp{
		width: 200px;
		height: 200px;
		border-color: currentColor;
	}
</style>