config/routes.rb
Rails.application.routes.draw do

  get 'publications/new'
  get 'publications/create'
  get 'publications/edit'
  get 'publications/show'
  get 'publications/index'
  get 'publications/update'
  get 'publications/destroy'
  get 'avatars/create'
  get 'avatars/show'
  root 'static_pages#index'
  resources :requests
  resources :events do
    resources :commentaire
    resources :likes
  end
  resources :recrutements
  resources :clubs do
  	resources :pictures
  end
  resources :quarters
  devise_for :users
  resources :users do
    resources :avatars
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  include Trestle::Auth::ModelMethods
  include Trestle::Auth::ModelMethods::Rememberable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/club.rb
class Club < ApplicationRecord
	belongs_to :admin, class_name: 'User', dependent: :destroy
	belongs_to :quarter, dependent: :destroy
	has_many :recrutements
	has_many :members, class_name: 'User'
	has_many :participants, through: :recrutements
	has_many :events
	has_one_attached :picture
end

app/models/commentaire.rb
class Commentaire < ApplicationRecord
	validates :content, presence: true
	belongs_to :user
	belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :club, dependent: :destroy
	has_many :commentaires	
	has_many :likes, dependent: :destroy

end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :event
	belongs_to :user
end

app/models/publication.rb
class Publication < ApplicationRecord
	belongs_to :user, dependent: :destroy
end

app/models/quarter.rb
class Quarter < ApplicationRecord
	has_many :clubs
	has_many :users
end

app/models/recrutement.rb
class Recrutement < ApplicationRecord
	has_many :requests
	belongs_to :club, dependent: :destroy
end

app/models/request.rb
class Request < ApplicationRecord
	belongs_to :recrutement, dependent: :destroy, dependent: :destroy
	belongs_to :user, dependent: :destroy
end

app/models/router.rb
class Router < ApplicationRecord
end

app/models/static_page.rb
class StaticPage < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         belongs_to :quarter, optional: true
         belongs_to :club, optional: true
         has_many :requests
         has_many :commentaires
         has_many :likes, dependent: :destroy
         has_one_attached :avatar
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
        @event = Event.find(params[:id])
           @event_comments_count = @event.commentaires.all.count
  end

  # GET /events/new
  def new
   @event = Event.new
     @club = Club.find(params['data_value'])
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
  
    @event = Event.create('start_date' => params[:start_date], 'duration' => params[:duration], 'title' => params[:title], 'description' => params[:description], 'price' => params[:price],  'location' => params[:location],  club_id: params['club_id'])


    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end


    
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:start_date, :duration, :title, :description, :price, :location)
    end
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/quarters_helper.rb
module QuartersHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/routers_helper.rb
module RoutersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) :remote => true do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <%= form_tag url_for(action: 'create'), method: "event",:remote => true do %>
    <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %> >


  <div class="field">
    <%= label_tag :start_date %>
    <%= text_field_tag :start_date %>
  </div>

  <div class="field">
    <%= label_tag :duration %>
    <%= text_field_tag :duration %>
  </div>

  <div class="field">
    <%= label_tag :title %>
    <%= text_field_tag :title %>
  </div>

  <div class="field">
    <%= label_tag :description %>
    <%= text_field_tag :description %>
  </div>

  <div class="field">
    <%= label_tag :price %>
    <%= text_field_tag :price %>
  </div>

  <div class="field">
    <%= label_tag :location %>
    <%= text_field_tag :location %>
  </div>


    <div class="field">
    <input type="hidden" name="club_id" value="<%=@club.id%>">
  </div>

  <div class="actions">
     <%= submit_tag "creer event" %>
  </div>
<% end %>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Start date</th>
      <th>Duration</th>
      <th>Title</th>
      <th>Description</th>
      <th>Price</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.start_date %></td>
        <td><%= event.duration %></td>
        <td><%= event.title %></td>
        <td><%= event.description %></td>
        <td><%= event.price %></td>
        <td><%= event.location %></td>
        <td><%= link_to 'Show', event %></td>
        <% if user_signed_in? && current_user.role === 'admin' %>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% Club.all.each do |club| %>
<% if club.admin.id == current_user.id %>
<%= link_to 'New Event', new_event_path %>
<% end %>
<% end %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/new.js.erb
alert("L'événement a été créé avec succés");
document.getElementById("<%=@category.title%>").insertAdjacentHTML("beforeend", "<%= j render 'task', task: @task %>");

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start date:</strong>
  <%= @event.start_date %>
</p>

<p>
  <strong>Duration:</strong>
  <%= @event.duration %>
</p>

<p>
  <strong>Title:</strong>
  <%= @event.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @event.price %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>
 
  <%= link_to "commentaires", event_commentaire_index_path(params[:id])%>(<%= @event_comments_count%>)


<p><%= @event.likes.count %> <%= (@event.likes.count) == 1 ? 'Like' : 'Likes'%></p>
<%= button_to 'Like', event_likes_path(@event), method: :post %>


<% if @event.club.admin.id == current_user.id %>
<%= link_to 'Edit', edit_event_path(@event) %> |
<%end%>
<%= link_to '     Back', root_path %>