config/routes.rb
Rails.application.routes.draw do

  get 'publications/new'
  get 'publications/create'
  get 'publications/edit'
  get 'publications/show'
  get 'publications/index'
  get 'publications/update'
  get 'publications/destroy'
  get 'avatars/create'
  get 'avatars/show'
  root 'static_pages#index'
  resources :requests
  resources :events do
    resources :commentaire
    resources :likes
  end
  resources :recrutements
  resources :clubs do
  	resources :pictures
  end
  resources :quarters
  devise_for :users
  resources :users do
    resources :avatars
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  include Trestle::Auth::ModelMethods
  include Trestle::Auth::ModelMethods::Rememberable
end

app/models/club.rb
class Club < ApplicationRecord
	belongs_to :admin, class_name: 'User', dependent: :destroy
	belongs_to :quarter, dependent: :destroy
	has_many :recrutements
	has_many :members, class_name: 'User'
	has_many :participants, through: :recrutements
	has_many :events
	has_one_attached :picture
end

app/models/commentaire.rb
class Commentaire < ApplicationRecord
	validates :content, presence: true
	belongs_to :user
	belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :club, dependent: :destroy
	has_many :commentaires	
	has_many :likes, dependent: :destroy

end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :event
	belongs_to :user
end

app/models/publication.rb
class Publication < ApplicationRecord
	belongs_to :user, dependent: :destroy
end

app/models/quarter.rb
class Quarter < ApplicationRecord
	has_many :clubs
	has_many :users
end

app/models/recrutement.rb
class Recrutement < ApplicationRecord
	has_many :requests
	belongs_to :club, dependent: :destroy
end

app/models/request.rb
class Request < ApplicationRecord
	belongs_to :recrutement, dependent: :destroy, dependent: :destroy
	belongs_to :user, dependent: :destroy
end

app/models/router.rb
class Router < ApplicationRecord
end

app/models/static_page.rb
class StaticPage < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         belongs_to :quarter, optional: true
         belongs_to :club, optional: true
         has_many :requests
         has_many :commentaires
         has_many :likes, dependent: :destroy
         has_one_attached :avatar
end

app/controllers/recrutements_controller.rb
class RecrutementsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_recrutement, only: [:show, :edit, :update, :destroy]

  # GET /recrutements
  # GET /recrutements.json
  def index
    @recrutements = Recrutement.all
  end

  # GET /recrutements/1
  # GET /recrutements/1.json
  def show
      @recrutement = Recrutement.find(params[:id])
  end

  # GET /recrutements/new
  def new
    @recrutement = Recrutement.new('content' => params[:content], 'deadline' => params[:deadline])
 @club = Club.find(params['data_value'])

  end

  # GET /recrutements/1/edit
  def edit
  end

  # POST /recrutements
  # POST /recrutements.json
  def create
   
    @recrutement = Recrutement.create('content' => params[:content], 'deadline' => params[:deadline], club_id: params['club_id'])

    respond_to do |format|
      if @recrutement.save
        format.html { redirect_to @recrutement, notice: 'Recrutement was successfully created.' }
        format.json { render :show, status: :created, location: @recrutement }
      else
        format.html { render :new }
        format.json { render json: @recrutement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recrutements/1
  # PATCH/PUT /recrutements/1.json
  def update
    @recrutement = Recrutement.find(params[:id])
    respond_to do |format|
      if @recrutement.update(content: params['content'], deadline:['deadline'])
        format.html { redirect_to @recrutement, notice: 'Recrutement was successfully updated.' }
        format.json { render :show, status: :ok, location: @recrutement }
      else
        format.html { render :edit }
        format.json { render json: @recrutement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recrutements/1
  # DELETE /recrutements/1.json
  def destroy
    @recrutement.destroy
    respond_to do |format|
      format.html { redirect_to recrutements_url, notice: 'Recrutement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recrutement
      @recrutement = Recrutement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recrutement_params
      params.require(:recrutement).permit(content: params['content'], deadline:['deadline'])
    end
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/quarters_helper.rb
module QuartersHelper
end

app/helpers/recrutements_helper.rb
module RecrutementsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/routers_helper.rb
module RoutersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/recrutements/_form.html.erb
<%= form_with(model: recrutement, local: true) do |form| %>
  <% if recrutement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recrutement.errors.count, "error") %> prohibited this recrutement from being saved:</h2>

      <ul>
        <% recrutement.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <%= form_tag url_for(action: 'create'), method: "recrutement" do %>
    <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %> >

  <div class="field">
    <%= label_tag :content %>
    <%= text_area_tag :content, @recrutement.content  %>
  </div>
  <div class="field">
    <input type="hidden" name="club_id" value="<%=@club.id%>">
  </div>

  <div class="field">
    <%= label_tag :deadline %>
    <%= date_field_tag :deadline, @recrutement.deadline %>
  </div>

  <div class="actions">
    <%= submit_tag "creer recrutement" %>
  </div>
<% end %>
<% end %>

app/views/recrutements/_update.html.erb
   <%= form_tag url_for(action: 'update'), method: "patch" do |form|%>
    <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %> >


  <div class="field">
    <%= label_tag :content %>
    <%= text_area_tag :content, @recrutement.content %>
  </div>


   <div class="field">
    <%= label_tag :deadline %>
    <%= date_field_tag :deadline, @recrutement.deadline %>
  </div>
  

  
<div class="field">
    <input type="hidden" name="recrutement_id" value="<%= @recrutement.id%>">
  </div>



  <div class="actions">
    <%= submit_tag %>
  </div>
<% end %>

app/views/recrutements/edit.html.erb
<h1>Editing Recrutement</h1>

<%= render 'update', recrutement: @recrutement %>

<%= link_to 'Show', @recrutement %> |
<%= link_to 'Back', recrutements_path %>

app/views/recrutements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recrutements</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Deadline</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recrutements.each do |recrutement| %>
      <tr>
        <td><%= recrutement.content %></td>
        <td><%= recrutement.deadline %></td>
        <td><%= link_to 'Show', recrutement %></td>

<% if current_user == recrutement.club.admin %>
        <td><%= link_to 'Edit', edit_recrutement_path(recrutement) %></td>
        <td><%= link_to 'Destroy', recrutement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/recrutements/new.html.erb
<h1>New Recrutement</h1>

<%= render 'form', recrutement: @recrutement %>

<%= link_to 'Back', recrutements_path %>

app/views/recrutements/show.html.erb
<p id="notice"><%= notice %></p>

      <h1>Hello! vous etes sur le recrutement du club  <%= @recrutement.club.name %> </h1>
      <p><strong>Deadline:</strong>
  <%= @recrutement.deadline %></p>

<%= link_to 'Edit', edit_recrutement_path(@recrutement) %> |
<%= link_to 'Back', recrutements_path %>


  <br/>
<br/>
<br/>
        <h1>Listes des demandes</h1>
<% if @recrutement.club.admin.id == current_user.id%>
<% @recrutement.club.members.each do |member| %>
<% if member.id == current_user.id%>
    <a id="<%= @recrutement.id %>" href="#" role="button" >Postuler &raquo;</a>
<% end %>
<% end %>
<% end %>

 
        <p>pour acceder a la page d un demande clique sur son blue nom</p>
        </div>
      </div>
 <% @recrutement.requests.each do |request| %>
 <% if request.user.club == request.recrutement.club%>
 <%else%>

                <h3>Nom demandeur: <%= link_to "#{request.user.first_name}", user_path(request.user.id) %>    <%= request.user.last_name %> </h3>
                <h3> <%= link_to "Afficher", request_path(request.id) %> </h3>

           <p>Age: <%= request.user.age %></p>
            <% end %>
            <% end %>